### PR TITLE
Do not symlink the project's node_modules directory

### LINKED ISSUE #173: link task removes dependencies from node_modules
Within a Dojo cli project like cli-test-intern, I do the following to test my changes:

```
grunt dist
grunt link
```
The `grunt link` command removes modules from `node_modules` so if I want to run `grunt dist` again, I have to first run `npm install`.  So my workflow is  `grunt dist; grunt link; npm i`.

I'm not sure why `grunt link` is mangling `node_modules` but is there a way the `grunt link` task could restore `node_modules` as a last step?

### PR DESCRIPTION
**Pull request by edhager**
When the `link` task creates a symlink in dist/umd to the project's node_modules directory, the ensuing `npm link` command does an `npm install` in dist/umd but it removes the dev dependencies from the project's' node_modules directory.  This causes a bit of confusion when the dev runs `grunt dist` again and it fails because of missing modules.  This PR fixes that by not creating the node_modules symlink.

One side effect...  If the project's package.json is updated after running `grunt dist`, `dist/umd/node_modules` will no longer match.  The dev can run `grunt link` again or go to `dist/umd` and run `npm install`.

Resolves #173

### CODE REVIEW

**Comment by edhager** [comment]
I'm adding more unit tests to increase the coverage.

**Comment by edhager** [comment]
I added unit tests to increase the coverage percentage.  I did not create one for `options/typedoc.ts` because that will be removed soon.  The tests I added are not that valuable but increasing the coverages means that code changes like my original change in this PR have less effect on the coverage percentage.  In my change, I removed some code and that small change caused the build to fail because of the drop in coverage percentage.

**Comment by edhager** [comment]
The workflow is still broken.  Now `dojo link` does not mangle node_modules but `dojo dist` deletes  dist/umd/node_modules.  It should not do that.

**Comment by agubler** [comment]
We don't use grunt-dojo2 for the dojo development pipeline for most of our repositories with the rest scheduled to migrate to dojo/scripts.

**Pull request closed without merging**
