### PR TITLE
Remove legacy TS compiler config

### PR DESCRIPTION
**Pull request by agubler**
now all dojo modules have been upgraded to TS2, the legacy configurations can be removed.

### CODE REVIEW

**Comment by kitsonk** [comment]
Do we want to drop DTS Generator too?  If we have fully converted to UMD Definitions, we should drop the `typings` from the `package.json` and stop generating the global `d.ts`

**Comment by agubler** [comment]
sure, I'll drop the dts generator from dist pipeline.

**Comment by agubler** [comment]
@kit removed dts generator and updatetsconfig

**Comment by matt-gadd** [comment]
👍

**Pull request merged**
