### PR TITLE
Unit tests for grunt-dojo2, fixes #1

### LINKED ISSUE #1: Create Unit Tests
We need to create unit tests for the following:
- [ ] tasks/rename
- [ ] tasks/rewriteSourceMaps
- [ ] tasks/updateTsconfig
- [ ] tasks/uploadCoverage

### PR DESCRIPTION
**Pull request by rorticus**
Unit tests!

I had to add a few dependencies to help with the testing, `mockery` and `sinon`.

### CODE REVIEW

**Comment by agubler** [comment]
How come the tests are written in js?

**Comment by agubler** [comment]
> I'd be happy to convert them to TS though, just let me know.

Happy? In that case.... 😄 In all seriousness I do think that the tests should be TS

**Comment by rorticus** [comment]
> I do think that the tests should be TS

So you have wished it, so it shall be!

**Comment by rorticus** [comment]
OK! It's all TypeScripted it up now!

**Pull request merged**
