### PR TITLE
Integrate Reporter.ts.

### PR DESCRIPTION
**Pull request by lzhoucs**
This moves `Reporter.ts` into this repo(`grunt-dojo2`). Because `Reporter.ts` will no longer be included in each dojo2 package, for intern to load `Reporter.ts` in this repo, each package will need to specify `grunt-dojo2` location in the intern config(unless there's a better way to do it, for which please let me know):
```js
{ name: 'grunt-dojo2', location: 'node_modules/grunt-dojo2'}

```
Depends on: https://github.com/dojo/core/pull/283
Resolves: #61

### CODE REVIEW

**Comment by lzhoucs** [comment]
Will cleanup all the packages and update `dojo2-package-template` next.

**Comment by agubler** [comment]
Could we as part of this move the intern config also?

**Comment by lzhoucs** [comment]
@agubler , I think that is a good idea. Will look at that later this week. Thanks!

**Comment by lzhoucs** [comment]
I When [intern's PreExecutor loads intern config](https://github.com/theintern/intern/blob/3.4/lib/executors/PreExecutor.js#L143), it doesn't currently support loading it from a "package" where the location can be configured in its ["meta config"](https://github.com/theintern/intern/blob/3.4/client.js#L7). So for intern config path, whatever comes from `grunt-dojo2` needs to be "final". Which means if we want to put intern config inside `grunt-dojo2`, we have to hard code its path in [options/intern.ts](https://github.com/dojo/grunt-dojo2/blob/master/options/intern.ts#L7) to something like following:
```js
config: 'node_modules/grunt-dojo2/tests/intern'
```
I can't do the following and config `grunt-dojo2` location somewhere as I did for the `Reporter.ts`
```js
config: 'grunt-dojo2/tests/intern'
```
On the other hand, each dojo2 package may or may not want to have its unique part of intern config, by sharing one config, this becomes impossible unless intern supports load from multiple configs.

The benefit of having one copy of config is obvious also. For example, we don't have to go to each package and add `grunt-dojo2` location anymore. With one config, we can just update one place.

@agubler please let me know what you think. If you don't see any issue with my concern, I'll go ahead and make the intern config change. Otherwise I'll just clean up all the packages.

**Comment by agubler** [comment]
@lzhoucs I think this is a good start, we can follow up with moving the intern config.

**Comment by matt-gadd** [comment]
Just a note on this PR. We use `grunt-dojo2` unpinned in our dojo 2 projects. Because this was a breaking change and was neither backwards nor forwards compatible, it was always going to break **all** of our downstream projects at some point.

If we'd have added a check in `index.ts` for the existence of the reporter in `test` before switching the config path to the reporter this would've been both backwards and forwards compatible I believe.

In future we should either pin `grunt-dojo2` (or at least specify a semver range, so we can bump the major version) or be a little more conscious on backwards/forwards compatibility.

**Comment by agubler** [comment]
@matt-gadd Thank you, you are right and that is my mistake. In future I will ensure I am conscientious about that.

**Comment by lzhoucs** [comment]
I agree with @matt-gadd 's concern. However I don't see any *breaking* part of changes. Please correct me if I am wrong. The only change so far is the relocation of the `Reporter.ts` and this file should be the same in all downsteam projects. And the new `Reporter.ts` is readily available within `grunt-dojo2` so I don't see a necessity to add the check for the existence of the old one.

**Comment by matt-gadd** [comment]
@lzhoucs removing https://github.com/dojo/grunt-dojo2/pull/99/files#diff-ed009b6b86b017532ef0489c77de5100L110, made this a breaking change.

**Comment by lzhoucs** [comment]
@matt-gadd , thanks for the quick reply. Sorry I still don't see what this line breaks. Yes, It is updating the path of the `Reporter.ts`, but the new path of this file is already available. So in downstream projects, we should see no difference before or after this change. All they need to do is some clean up - remove the out dated `Reporter.ts` in the individual projects.

**Comment by matt-gadd** [comment]
@lzhoucs thats not true unfortunately, all downstream apps then needed a path mapping to `grunt-dojo2` in their intern config for it to work.

**Comment by agubler** [comment]
@lzhoucs it was indeed breaking until either I merged the PRs you had raised to add the path or created the PRs myself for the missing ones.

**Comment by lzhoucs** [comment]
@agubler @matt-gadd , thanks for the reply! Now I see what is going on! Sorry for the confusion. Yes, the downstream ones will need a mapping of `grunt-dojo2` as I added into some of the cleanup PRs. And I definitely agree that adding a check is better in this case, until all the cleanup PRs are landed!

**Pull request merged**
